##### https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/quick-start-guide.md
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: techitalia
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: techitalia
  name: spark-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: techitalia
subjects:
- kind: ServiceAccount
  name: spark
  namespace: techitalia
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: parquet-pv
  namespace: techitalia
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  hostPath:
    path: "REPLACE_ME"
    type: ''
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: parquet-pv-claim
  namespace: techitalia
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeName: parquet-pv
  storageClassName: hostpath
---
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-techitalia
  namespace: techitalia
spec:
  volumes:
    - name: parquet
      persistentVolumeClaim:
        claimName: parquet-pv-claim
  type: Java
  mode: cluster
  image: "luciferino/mongosparkstreaming:0.0.1"
  imagePullPolicy: Always
  mainClass: it.arubapec.esecurity.mongostreamspark.SpringKafkaApplication
  mainApplicationFile: "local:///opt/spark/examples/jars/app.jar/app.jar"
  sparkVersion: "2.4.4"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 2.4.4
    serviceAccount: spark
    volumeMounts:
      - name: parquet
        mountPath: "/Users/luca/.kubernetes/shared/parquet"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.4
