---
apiVersion: v1
kind: Namespace
metadata:
  name: registry
  labels:
    name: registry
---
apiVersion: v1
kind: Namespace
metadata:
  name: techitalia
  labels:
    name: techitalia
