kind: Service
apiVersion: v1
metadata:
  name: zeppelin-server
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: rpc
      protocol: TCP
      port: 12320
      targetPort: 12320
  selector:
    app: zeppelin-server
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
