kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka
  namespace: techitalia
  labels:
    k8s-app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kafka
  template:
    metadata:
      name: kafka
      creationTimestamp: null
      labels:
        k8s-app: kafka
    spec:
      containers:
        - name: kafka
          image: johnnypark/kafka-zookeeper
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: 'PLAINTEXT://kafka.techitalia:9092'
            - name: ADVERTISED_LISTENERS
              value: kafka.techitalia
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: kafka
  namespace: techitalia
  labels:
    k8s-app: kafka
spec:
  ports:
  - name: tcp-2181-2181-z7jlf
    protocol: TCP
    port: 2181
    targetPort: 2181
    nodePort: 31690
  - name: tcp-9092-9092-f6h2f
    protocol: TCP
    port: 9092
    targetPort: 9092
    nodePort: 30400
  selector:
    k8s-app: kafka
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
