---
apiVersion: v1
kind: Service
metadata:
  name: kube-registry
  namespace: registry
  labels:
    k8s-app: registry
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeRegistry"
spec:
  selector:
    k8s-app: registry
  ports:
  - name: registry
    port: 5000
    targetPort: 5000
    protocol: TCP
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster