### Kafka Manager
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-manager
  namespace: techitalia
  labels:
    k8s-app: kafka-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kafka-manager
  template:
    metadata:
      name: kafka-manager
      labels:
        k8s-app: kafka-manager
    spec:
      containers:
        - name: kafka-manager
          image: 'hlebalbau/kafka-manager:stable'
          env:
            - name: ZK_HOSTS
              value: 'kafka.techitalia:2181'
            - name: APPLICATION_SECRET
              value: random-secret
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      hostAliases:
        - ip: 10.111.143.18
          hostnames:
            - kafka-8587c7c85c-b7pqr
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
### Kafka Manager Service
kind: Service
apiVersion: v1
metadata:
  name: kafka-manager
  namespace: techitalia
  labels:
    k8s-app: kafka-manager
spec:
  ports:
    - name: tcp-9000-9006-qcn8r
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 31277
  selector:
    k8s-app: kafka-manager
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster