kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-connect
  namespace: techitalia
  selfLink: /apis/apps/v1/namespaces/techitalia/deployments/kafka-connect
  uid: 1d6e9b47-00f9-11ea-83f2-025000000001
  resourceVersion: '32671'
  generation: 2
  creationTimestamp: '2019-11-07T00:54:12Z'
  labels:
    k8s-app: kafka-connect
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 0
  selector:
    matchLabels:
      k8s-app: kafka-connect
  template:
    metadata:
      name: kafka-connect
      creationTimestamp: null
      labels:
        k8s-app: kafka-connect
    spec:
      containers:
        - name: kafka-connect
          image: confluentinc/cp-kafka-connect
          env:
            - name: CONNECT_GROUP_ID
              value: quickstart
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: 'mongodb.techitalia:27017'
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: quickstart-config
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: quickstart-offsets
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: quickstart-status
            - name: CONNECT_KEY_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_VALUE_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_INTERNAL_KEY_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_INTERNAL_VALUE_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              value: localhost
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 2
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2019-11-07T00:54:16Z'
      lastTransitionTime: '2019-11-07T00:54:12Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "kafka-connect-6db4b895cf" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2019-11-07T01:01:00Z'
      lastTransitionTime: '2019-11-07T01:01:00Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
