---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: registry-pv
  namespace: registry
  labels:
    type: local
spec:
  capacity:
    storage: 50Gi
  hostPath:
    path: "REPLACE_ME"
    type: ''
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registry-pv-claim
  namespace: registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: registry-pv
  storageClassName: hostpath
status:
  phase: Bound
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-registry-v0
  namespace: registry
  labels:
    k8s-app: registry
    version: v0
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: registry
    version: v0
  template:
    metadata:
      labels:
        k8s-app: registry
        version: v0
        kubernetes.io/cluster-service: "true"
    spec:
      volumes:
      - name: image-store
        persistentVolumeClaim:
          claimName: registry-pv-claim
      containers:
      - name: registry
        image: registry:2
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        volumeMounts:
        - name: image-store
          mountPath: /var/lib/registry
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP