---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-pv
  namespace: techitalia
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  hostPath:
    path: "/Users/luca/kubernetes/mongodb"
    type: ''
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pv-claim
  namespace: techitalia
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: mongodb-pv
  storageClassName: hostpath
status:
  phase: Bound
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
---
### MONGODB - Deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb
  namespace: techitalia
  labels:
    k8s-app: mongodb
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mongodb
  template:
    metadata:
      name: mongodb
      creationTimestamp: null
      labels:
        k8s-app: mongodb
    spec:
      volumes:
      - name: mongodb
        hostPath:
        persistentVolumeClaim:
          claimName: mongodb-pv-claim
      - name: mongo-init
        secret:
          secretName: mongo-init
          defaultMode: 420
      containers:
        - name: mongodb
          image: 'bitnami/mongodb:latest'
          env:
            - name: MONGODB_REPLICA_SET_MODE
              value: primary
            - name: MONGODB_ROOT_PASSWORD
              value: password123
            - name: MONGODB_ADVERTISED_HOSTNAME
              value: mongodb.techitalia
            - name: MONGODB_PRIMARY_HOST
              value: mongodb.techitalia
            - name: MONGODB_REPLICA_SET_KEY
              value: replicasetkey123
            - name: MONGODB_USERNAME
              value: tech
            - name: MONGODB_PASSWORD
              value: italia
            - name: MONGODB_DATABASE
              value: techitalia
          resources: {}
          volumeMounts:
          - name: mongodb
            mountPath: "/data/db"
          volumeMounts:
          - name: mongo-init
            mountPath: "/docker-entrypoint-initdb.d"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
