---
### Kafka Manager
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-manager
  namespace: REPLACE_NAMESPACE
  labels:
    k8s-app: kafka-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kafka-manager
  template:
    metadata:
      name: kafka-manager
      labels:
        k8s-app: kafka-manager
    spec:
      containers:
        - name: kafka-manager
          image: 'hlebalbau/kafka-manager:stable'
          env:
            - name: ZK_HOSTS
              value: 'kafka.REPLACE_NAMESPACE:2181'
            - name: APPLICATION_SECRET
              value: random-secret
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
